import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..");
const opcodeSourceCandidates = [
  resolve(repoRoot, "tools", "OpCode.cs"),
  resolve(repoRoot, "neo_csharp", "vm", "src", "Neo.VM", "OpCode.cs"),
];

const outputPath = resolve(repoRoot, "js", "src", "generated", "opcodes.js");

function resolveOpcodeSource() {
  for (const candidate of opcodeSourceCandidates) {
    try {
      readFileSync(candidate, "utf8");
      return candidate;
    } catch {}
  }
  throw new Error(
    `Missing opcode source. Looked for ${opcodeSourceCandidates.join(", ")}`,
  );
}

function toJsName(name) {
  const specialPrefix = new Map([
    ["PUSHINT", (suffix) => `Pushint${suffix}`],
    ["PUSHDATA", (suffix) => `Pushdata${suffix}`],
    ["PUSH", (suffix) => `Push${titleCase(suffix)}`],
    ["JMPIFNOT", (suffix) => `Jmpifnot${titleCase(suffix)}`],
    ["JMPIF", (suffix) => `Jmpif${titleCase(suffix)}`],
    ["JMP", (suffix) => `Jmp${titleCase(suffix)}`],
    ["CALL", (suffix) => `Call${titleCase(suffix)}`],
    ["INITSSLOT", (suffix) => `Initsslot${titleCase(suffix)}`],
    ["INITSLOT", (suffix) => `Initslot${titleCase(suffix)}`],
  ]);

  for (const [prefix, build] of specialPrefix) {
    if (name.startsWith(prefix)) {
      return build(name.slice(prefix.length));
    }
  }

  return titleCase(name.toLowerCase().replaceAll("_", " "));
}

function titleCase(value) {
  return value
    .split(" ")
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");
}

function operandEncoding(name) {
  if (name.startsWith("PUSHINT")) {
    const size = Number(name.slice("PUSHINT".length));
    const mapping = new Map([
      [8, "I8"],
      [16, "I16"],
      [32, "I32"],
      [64, "I64"],
    ]);
    if (mapping.has(size)) {
      return mapping.get(size);
    }
    return ["Bytes", size / 8];
  }

  if (name === "PUSHA") return "U32";
  if (name === "PUSHDATA1") return "Data1";
  if (name === "PUSHDATA2") return "Data2";
  if (name === "PUSHDATA4") return "Data4";

  const shortTargets = new Set([
    "JMP",
    "JMPIF",
    "JMPIFNOT",
    "JMPEQ",
    "JMPNE",
    "JMPGT",
    "JMPGE",
    "JMPLT",
    "JMPLE",
    "CALL",
    "ENDTRY",
  ]);

  if (shortTargets.has(name)) return "Jump8";
  if (shortTargets.has(name.replace(/_L$/, "")) && name.endsWith("_L")) {
    return "Jump32";
  }
  if (name === "CALLT") return "U16";
  if (name === "TRY") return ["Bytes", 2];
  if (name === "TRY_L") return ["Bytes", 8];
  if (name === "SYSCALL") return "Syscall";
  if (
    [
      "INITSSLOT",
      "LDSFLD",
      "STSFLD",
      "LDLOC",
      "STLOC",
      "LDARG",
      "STARG",
      "NEWARRAY_T",
      "ISTYPE",
      "CONVERT",
    ].includes(name)
  ) {
    return "U8";
  }
  if (name === "INITSLOT") return ["Bytes", 2];
  return "None";
}

function parseEntries(sourceText) {
  const pattern =
    /(?:\[OperandSize\([^\]]*\)\]\s*)?(\w+)\s*=\s*0x([0-9A-Fa-f]{2})/g;
  const entries = [];
  for (const match of sourceText.matchAll(pattern)) {
    entries.push({
      sourceName: match[1],
      byte: Number.parseInt(match[2], 16),
    });
  }
  return entries;
}

function renderEncoding(value) {
  if (Array.isArray(value)) {
    return JSON.stringify({ kind: value[0], length: value[1] });
  }
  return JSON.stringify({ kind: value });
}

const sourcePath = resolveOpcodeSource();
const sourceText = readFileSync(sourcePath, "utf8");
const entries = parseEntries(sourceText)
  .sort((left, right) => left.byte - right.byte)
  .map(({ sourceName, byte }) => ({
    name: toJsName(sourceName),
    mnemonic: sourceName,
    byte,
    operandEncoding: operandEncoding(sourceName),
  }));

mkdirSync(dirname(outputPath), { recursive: true });

const body = `// This file is @generated by js/scripts/generate-opcodes.mjs. Do not edit manually.
export const OPCODES = new Map([
${entries
  .map(
    (entry) =>
      `  [0x${entry.byte.toString(16).padStart(2, "0").toUpperCase()}, { name: ${JSON.stringify(entry.name)}, mnemonic: ${JSON.stringify(entry.mnemonic)}, byte: 0x${entry.byte
        .toString(16)
        .padStart(2, "0")
        .toUpperCase()}, operandEncoding: ${renderEncoding(entry.operandEncoding)} }],`,
  )
  .join("\n")}
]);
`;

writeFileSync(outputPath, body);
console.log(`wrote ${outputPath}`);
