# Neo N3 Decompiler Configuration

[analysis]
enable_type_inference = true
enable_effect_analysis = true
enable_cfg_analysis = true
enable_loop_detection = true
enable_dead_code_elimination = false
max_analysis_depth = 100
analysis_timeout = 30
parallel_analysis = true

[output]
syntax_style = "CStyle"  # CStyle, Python, Rust, TypeScript
include_type_annotations = true
include_ir_comments = false
indent_size = 4
max_line_length = 100
generate_reports = false
include_performance_metrics = false

[plugins]
enabled = true
plugin_paths = ["./plugins", "~/.neo-decompiler/plugins"]
enabled_plugins = ["syscall_analyzer", "nep_detector", "vulnerability_scanner"]
plugin_timeout = 10

[performance]
parallel_processing = true
# worker_threads = 8  # Uncomment to override auto-detection
memory_limit_mb = 1024
enable_caching = true
cache_size_limit = 10000

[syscalls]
syscall_definitions_path = "./config/syscalls"
enable_effect_analysis = true