# NEP-17 Token Standard Configuration

[standard]
name = "NEP-17"
version = "1.0"
description = "Fungible Token Standard"
specification_url = "https://github.com/neo-project/proposals/blob/master/nep-17.md"

# Required methods for NEP-17 compliance
[[required_methods]]
name = "symbol"
parameters = []
return_type = "String"
description = "Returns the token symbol"

[[required_methods]]
name = "decimals"
parameters = []
return_type = "Integer"
description = "Returns the number of decimal places"

[[required_methods]]
name = "totalSupply"
parameters = []
return_type = "Integer"
description = "Returns the total supply of tokens"

[[required_methods]]
name = "balanceOf"
parameters = ["Hash160"]
return_type = "Integer"
description = "Returns the balance of an account"

[[required_methods]]
name = "transfer"
parameters = ["Hash160", "Hash160", "Integer", "Any"]
return_type = "Boolean"
description = "Transfers tokens from one account to another"

# Required events
[[required_events]]
name = "Transfer"
parameters = ["Hash160", "Hash160", "Integer"]
description = "Emitted when tokens are transferred"

# Optional methods
[[optional_methods]]
name = "name"
parameters = []
return_type = "String"
description = "Returns the token name"

# Interface detection patterns
[detection]
# Method signatures that indicate NEP-17 compliance
method_signatures = [
    "symbol",
    "decimals",
    "totalSupply",
    "balanceOf",
    "transfer"
]

# Event signatures
event_signatures = [
    "Transfer"
]

# Storage key patterns commonly used in NEP-17 tokens
storage_patterns = [
    "balance_",
    "totalSupply",
    "name",
    "symbol",
    "decimals"
]

# Common syscalls used in NEP-17 implementations
common_syscalls = [
    "System.Storage.Get",
    "System.Storage.Put",
    "System.Runtime.CheckWitness",
    "System.Runtime.Notify"
]